import {
  CreateDateColumn,
  DeleteDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * Shared columns for every persisted entity:
 *  - `id`         : uuid v4 (server-generated by Postgres' pgcrypto/uuid-ossp).
 *  - `createdAt`  : insert timestamp, set by the DB.
 *  - `updatedAt`  : auto-bumped on every update.
 *  - `deletedAt`  : soft-delete marker; null until softRemove() is called.
 *
 * Extend this in every entity instead of redeclaring the same four fields.
 */
export abstract class BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt!: Date;

  @DeleteDateColumn({ type: 'timestamptz', nullable: true })
  deletedAt!: Date | null;
}
